apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.godotview'
version = '1.0.0'

android {
  namespace "expo.modules.godotview"
  compileSdkVersion 34

  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 34
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }

  kotlinOptions {
    jvmTarget = '17'
  }

  // Prevent compression of Godot asset files for sparse pack random access
  aaptOptions {
    noCompress 'sparsepck', 'pck', 'bin', 'cfg', 'ctex', 'mp3str',
               'gdc', 'tscn', 'import', 'tres', 'remap', 'res',
               'scn', 'gdshader', 'binary', 'translation'
  }

  androidResources {
    // Do not ignore any assets so .godot is packaged.
    ignoreAssetsPattern ''
  }
}

repositories {
  mavenCentral()
  flatDir {
    dirs 'libs'
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.0"
  implementation "androidx.fragment:fragment-ktx:1.8.2"
  
  // Godot library
  implementation(name: 'godot-lib.4.6.stable.template_release', ext: 'aar')
}
